Fix/missing parent for receipt
near/near-indexer-for-explorer pull request #39
Opened 2020-11-05 11:49 UTC by khorolets

It appears to happen only in case of data-receipts, because we can't find previous receipt by `receipt_id`. Instead we need to look for receipt via `data_id` through `receipts_action_output_data`. I've changed the way we're looking for parent transaction for receipts to differentiate action-receipts and data-receipts.

2020-11-05 17:26 UTC, bowenwang1996 commented
why do you need to store data receipts?

2020-11-05 17:31 UTC, khorolets commented
@bowenwang1996 to represent what is happening on the chain in Explorer

2020-11-05 20:02 UTC, frol commented
@bowenwang1996 Our goal is to represent all the events happening on the network. Do you think it is pointless to expose data receipts to contract developers?

2020-11-05 22:13 UTC, frol requested changes
We need the index over the `data_id` as otherwise, it will be too slow with the number of growing data receipts.

Other than that, everything looks good to me!

2020-11-06 12:57 UTC, frol approved these changes

2020-11-09 13:15 UTC, merged